SELECT *
FROM SalesReport

--Standardize data format
SELECT SalesDateConverted, CONVERT(Date, DATE)
FROM SalesReport

ALTER TABLE SalesReport
ADD SalesDateConverted Date

UPDATE SalesReport
SET SalesDateConverted = CONVERT(Date, DATE)

EXEC sp_rename 'SalesReport.SalesDateConverted', 'SaleDateConverted', 'COLUMN';
EXEC sp_rename 'SalesReport.GROSS AMT', 'GROSSAMT', 'COLUMN'

SELECT MonthsConverted, CONVERT(Date, Months)
FROM SalesReport

ALTER TABLE SalesReport 
ADD MonthsConverted DATE

UPDATE SalesReport
SET MonthsConverted = CONVERT(Date, Months)

SELECT
PARSENAME(REPLACE(MonthsConverted, '-', '.'), 2)
FROM SalesReport

ALTER TABLE SalesReport
ADD SaleMonthsConverted nvarchar(255)

UPDATE SalesReport
SET SaleMonthsConverted = PARSENAME(REPLACE(MonthsConverted, '-', '.'), 2)


--Changing unrelared value in a  customer column would be NULL
SELECT CUSTOMER
FROM SalesReport
GROUP BY CUSTOMER

SELECT CUSTOMER,
CASE
	WHEN CUSTOMER = 'Feb-22' THEN NULL
	WHEN CUSTOMER = 'Oct-21' THEN NULL
	WHEN CUSTOMER = 'Jan-22' THEN NULL
	WHEN CUSTOMER = 'Jul-21' THEN NULL
	WHEN CUSTOMER = 'Dec-21' THEN NULL
	WHEN CUSTOMER = 'Jun-21' THEN NULL
	WHEN CUSTOMER = 'Nov-21' THEN NULL
	WHEN CUSTOMER = 'Aug-21' THEN NULL
	WHEN CUSTOMER = 'Sep-21' THEN NULL
	WHEN CUSTOMER = 'Mar-22' THEN NULL
	WHEN CUSTOMER = 'Months' THEN NULL
	ELSE CUSTOMER
	END
FROM SalesReport
GROUP BY CUSTOMER

ALTER TABLE SalesReport
ADD FixedCustomer nvarchar(255)

UPDATE SalesReport
SET FixedCustomer = CASE
	WHEN CUSTOMER = 'Feb-22' THEN NULL
	WHEN CUSTOMER = 'Oct-21' THEN NULL
	WHEN CUSTOMER = 'Jan-22' THEN NULL
	WHEN CUSTOMER = 'Jul-21' THEN NULL
	WHEN CUSTOMER = 'Dec-21' THEN NULL
	WHEN CUSTOMER = 'Jun-21' THEN NULL
	WHEN CUSTOMER = 'Nov-21' THEN NULL
	WHEN CUSTOMER = 'Aug-21' THEN NULL
	WHEN CUSTOMER = 'Sep-21' THEN NULL
	WHEN CUSTOMER = 'Mar-22' THEN NULL
	WHEN CUSTOMER = 'Months' THEN NULL
	ELSE CUSTOMER
	END

UPDATE SalesReport
SET FixedCustomer = UPPER(FixedCustomer)

SELECT Style
FROM SalesReport
GROUP BY Style


SELECT Style,
CASE
	WHEN Style = 'Jan-23' THEN NULL
	WHEN Style = 'Jan-18' THEN NULL
	WHEN Style = 'Jan-60' THEN NULL
	WHEN Style = 'Jan-22' THEN NULL
	WHEN Style = 'Jan-41' THEN NULL
	WHEN Style = 'Jan-61' THEN NULL
	WHEN Style = 'Jan-12' THEN NULL
	WHEN Style = 'TAG PRINTING' THEN NULL
	WHEN Style = 'Style' THEN NULL
	WHEN Style = 'SHIPPING' THEN NULL
	ELSE Style
	END
FROM SalesReport

ALTER TABLE SalesReport
ADD FixedStyle nvarchar(255)

UPDATE SalesReport
SET FixedStyle = CASE
	WHEN Style = 'Jan-23' THEN NULL
	WHEN Style = 'Jan-18' THEN NULL
	WHEN Style = 'Jan-60' THEN NULL
	WHEN Style = 'Jan-22' THEN NULL
	WHEN Style = 'Jan-41' THEN NULL
	WHEN Style = 'Jan-61' THEN NULL
	WHEN Style = 'Jan-12' THEN NULL
	WHEN Style = 'TAG PRINTING' THEN NULL
	WHEN Style = 'Style' THEN NULL
	WHEN Style = 'SHIPPING' THEN NULL
	ELSE Style
	END


SELECT SkuSize
FROM SalesReport
GROUP BY SkuSize
HAVING SkuSize NOT IN( 'XS','S', 'M', 'L', 'XL', 'XXL', '4XL', 'S TO XXL', '6XL', 'XXXL', '5XL' )

SELECT SkuSize,
CASE
	WHEN SkuSize = '164GOLD' THEN NULL
	WHEN SkuSize = '187GOLD' THEN NULL
	WHEN SkuSize =  '61BLACK' THEN NULL
	WHEN SkuSize =	'62BLACK' THEN NULL
    WHEN SkuSize =	'62PINK' THEN NULL
	WHEN SkuSize = 	'71RED' THEN NULL
	WHEN SkuSize =	'74BEIGE' THEN NULL
	WHEN SkuSize =	'74RED' THEN NULL
	WHEN SkuSize =	'78BEIGE' THEN NULL
	WHEN SkuSize =	'83RED' THEN NULL
	WHEN SkuSize =	'87BLACK' THEN NULL
	WHEN SkuSize =	'BL014' THEN NULL
	WHEN SkuSize =	'CHRAGE' THEN NULL
	WHEN SkuSize =	'FREE' THEN NULL
	WHEN SkuSize =	'JNE3826' THEN NULL
	WHEN SkuSize =	'JNE3827' THEN NULL
	WHEN SkuSize =	'JNE3828' THEN NULL
	WHEN SkuSize =	'JNE3829' THEN NULL
	WHEN SkuSize =	'JNE3830' THEN NULL
	WHEN SkuSize =	'JNE3831' THEN NULL
	WHEN SkuSize = 	'JNE3832' THEN NULL
	WHEN SkuSize =	'JNE3839' THEN NULL
	WHEN SkuSize =	'JNE3840' THEN NULL
	WHEN SkuSize = 	'JNE3843' THEN NULL
	WHEN SkuSize =	'JNE3844' THEN NULL
	WHEN SkuSize =	'JNE3845' THEN NULL
	WHEN SkuSize =	'JNE3846' THEN NULL
	WHEN SkuSize =	'JNE3847' THEN NULL
	WHEN SkuSize =	'JNE3848' THEN NULL
	WHEN SkuSize =	'JNE3849' THEN NULL
	WHEN SkuSize =	'JNE3850' THEN NULL
	WHEN SkuSize =	'JNE3851' THEN NULL
	WHEN SkuSize =	'JNE3852' THEN NULL
	WHEN SkuSize =	'JNE3853' THEN NULL
	WHEN SkuSize =	'JNE3855' THEN NULL
	WHEN SkuSize =	'JNE3857' THEN NULL
	WHEN SkuSize =	'JNE3858' THEN NULL
	WHEN SkuSize =	'KURTI' THEN NULL
	WHEN SkuSize =	'LABEL CHARGE' THEN NULL
	WHEN SkuSize =  'SAR027' THEN NULL
	WHEN SkuSize =  'SAR029' THEN NULL
	WHEN SkuSize = 'SAR031' THEN NULL
	WHEN SkuSize = 'SAR033' THEN NULL
	WHEN SkuSize = 'SAR038' THEN NULL
	WHEN SkuSize = 'SAR043' THEN NULL
	WHEN SkuSize = 'SAR044' THEN NULL
	WHEN SkuSize = 'SAR045' THEN NULL
	WHEN SkuSize = 'SAR046' THEN NULL
	WHEN SkuSize = 'SAR049' THEN NULL
	WHEN SkuSize = 'SAR050' THEN NULL
	WHEN SkuSize = 'SAR054' THEN NULL
	WHEN SkuSize = 'SAR070' THEN NULL
	WHEN SkuSize = 'SAR079' THEN NULL
	WHEN SkuSize = 'SAR086' THEN NULL
	WHEN SkuSize = 'SAREE' THEN NULL
	WHEN SkuSize = 'SC' THEN NULL
	WHEN SkuSize = 'SHIPPING' THEN NULL
	WHEN SkuSize = 'SHIPPING CHARGES' THEN NULL
	WHEN SkuSize = 'SKU' THEN NULL
	WHEN SkuSize = 'TAG PRINTING' THEN NULL
	WHEN SkuSize = 'TAGS' THEN NULL
	WHEN SkuSize = 'TAGS(LABOUR)' THEN NULL
	ELSE SkuSize
	END 
FROM SalesReport

UPDATE SalesReport
SET SkuSize = CASE
	WHEN SkuSize = '164GOLD' THEN NULL
	WHEN SkuSize = '187GOLD' THEN NULL
	WHEN SkuSize =  '61BLACK' THEN NULL
	WHEN SkuSize =	'62BLACK' THEN NULL
    WHEN SkuSize =	'62PINK' THEN NULL
	WHEN SkuSize = 	'71RED' THEN NULL
	WHEN SkuSize =	'74BEIGE' THEN NULL
	WHEN SkuSize =	'74RED' THEN NULL
	WHEN SkuSize =	'78BEIGE' THEN NULL
	WHEN SkuSize =	'83RED' THEN NULL
	WHEN SkuSize =	'87BLACK' THEN NULL
	WHEN SkuSize =	'BL014' THEN NULL
	WHEN SkuSize =	'CHRAGE' THEN NULL
	WHEN SkuSize =	'FREE' THEN NULL
	WHEN SkuSize =	'JNE3826' THEN NULL
	WHEN SkuSize =	'JNE3827' THEN NULL
	WHEN SkuSize =	'JNE3828' THEN NULL
	WHEN SkuSize =	'JNE3829' THEN NULL
	WHEN SkuSize =	'JNE3830' THEN NULL
	WHEN SkuSize =	'JNE3831' THEN NULL
	WHEN SkuSize = 	'JNE3832' THEN NULL
	WHEN SkuSize =	'JNE3839' THEN NULL
	WHEN SkuSize =	'JNE3840' THEN NULL
	WHEN SkuSize = 	'JNE3843' THEN NULL
	WHEN SkuSize =	'JNE3844' THEN NULL
	WHEN SkuSize =	'JNE3845' THEN NULL
	WHEN SkuSize =	'JNE3846' THEN NULL
	WHEN SkuSize =	'JNE3847' THEN NULL
	WHEN SkuSize =	'JNE3848' THEN NULL
	WHEN SkuSize =	'JNE3849' THEN NULL
	WHEN SkuSize =	'JNE3850' THEN NULL
	WHEN SkuSize =	'JNE3851' THEN NULL
	WHEN SkuSize =	'JNE3852' THEN NULL
	WHEN SkuSize =	'JNE3853' THEN NULL
	WHEN SkuSize =	'JNE3855' THEN NULL
	WHEN SkuSize =	'JNE3857' THEN NULL
	WHEN SkuSize =	'JNE3858' THEN NULL
	WHEN SkuSize =	'KURTI' THEN NULL
	WHEN SkuSize =	'LABEL CHARGE' THEN NULL
	WHEN SkuSize =  'SAR027' THEN NULL
	WHEN SkuSize =  'SAR029' THEN NULL
	WHEN SkuSize = 'SAR031' THEN NULL
	WHEN SkuSize = 'SAR033' THEN NULL
	WHEN SkuSize = 'SAR038' THEN NULL
	WHEN SkuSize = 'SAR043' THEN NULL
	WHEN SkuSize = 'SAR044' THEN NULL
	WHEN SkuSize = 'SAR045' THEN NULL
	WHEN SkuSize = 'SAR046' THEN NULL
	WHEN SkuSize = 'SAR049' THEN NULL
	WHEN SkuSize = 'SAR050' THEN NULL
	WHEN SkuSize = 'SAR054' THEN NULL
	WHEN SkuSize = 'SAR070' THEN NULL
	WHEN SkuSize = 'SAR079' THEN NULL
	WHEN SkuSize = 'SAR086' THEN NULL
	WHEN SkuSize = 'SAREE' THEN NULL
	WHEN SkuSize = 'SC' THEN NULL
	WHEN SkuSize = 'SHIPPING' THEN NULL
	WHEN SkuSize = 'SHIPPING CHARGES' THEN NULL
	WHEN SkuSize = 'SKU' THEN NULL
	WHEN SkuSize = 'TAG PRINTING' THEN NULL
	WHEN SkuSize = 'TAGS' THEN NULL
	WHEN SkuSize = 'TAGS(LABOUR)' THEN NULL
	ELSE SkuSize
	END 

SELECT SkuSize,
CASE
	WHEN SkuSize = '74PINK' THEN NULL
	WHEN SkuSize = '74BLACK' THEN NULL
	ELSE SkuSize
	END
FROM SalesReport

UPDATE SalesReport
SET SkuSize = CASE
	WHEN SkuSize = '74PINK' THEN NULL
	WHEN SkuSize = '74BLACK' THEN NULL
	ELSE SkuSize
	END

SELECT SkuSize
FROM SalesReport
GROUP BY SkuSize



--Breaking out SKU into two tables (SkuCode, SkuSize)

SELECT SKU
FROM SalesReport

SELECT 
PARSENAME(REPLACE(SKU, '-', '.'), 3) + '-' + 
PARSENAME(REPLACE(SKU, '-', '.'), 2),
PARSENAME(REPLACE(SKU, '-', '.'), 1)
FROM SalesReport

ALTER TABLE SalesReport
ADD SkuCode nvarchar(255)

ALTER TABLE SalesReport
ADD SkuSize nvarchar(255)

UPDATE SalesReport
SET SkuCode = PARSENAME(REPLACE(SKU, '-', '.'), 3) + '-' + 
PARSENAME(REPLACE(SKU, '-', '.'), 2)

UPDATE SalesReport
SET SkuSize = PARSENAME(REPLACE(SKU, '-', '.'), 1)




--Delete unsual column
ALTER TABLE SalesReport
DROP COLUMN MonthsConverted

ALTER TABLE SalesReport
DROP COLUMN DATE

ALTER TABLE SalesReport
DROP COLUMN Months

ALTER TABLE SalesReport
DROP COLUMN CUSTOMER

ALTER TABLE SalesReport
DROP COLUMN Style

ALTER TABLE SalesReport
DROP COLUMN SKU

ALTER TABLE SalesReport
DROP COLUMN Size

ALTER TABLE SalesReport
DROP COLUMN PCS

ALTER TABLE SalesReport
DROP COLUMN RATE

ALTER TABLE SalesReport
DROP COLUMN GROSSAMT

ALTER TABLE Salesreport
DROP COLUMN FixedPiece









